# Configuración de Conexión a la Base de Datos Supabase (PostgreSQL)
db.url=jdbc:postgresql://db.YOUR_SUPABASE_ID.supabase.co:5432/postgres
db.user=postgres
db.password=TU_CONTRASEÑA_SUPABASE

# Configuración API / Storage Supabase
supabase.url=https://YOUR_SUPABASE_ID.supabase.co
supabase.key=TU_SUPABASE_ANON_KEY